spring.application.name=demo
spring.ai.model.chat=google-genai
#spring.ai.google.genai.api-key=export SPRING_AI_GOOGLE_GENAI_API_KEY=$(op read "op://TW/GEMINI_API_KEY/credential")
spring.ai.google.genai.project-id=gen-lang-client-0767263214
